# This file specifies the settings the router should use when running

sandbox:
  enabled: true
supergraph:
  listen: "0.0.0.0:4000"
include_subgraph_errors:
  all: true
telemetry:
  instrumentation:
    spans:
      mode: spec_compliant
headers:
  all:
    request:
      - propagate:
          named: 'Authorization'
cors:
  policies:
    - origins:
        - https://sandbox.embed.apollographql.com
        - https://studio.apollographql.com
    - allow_credentials: true


subscription:
  enabled: true
  mode:
    callback:
      public_url: http://localhost:4005/callback
      listen: 0.0.0.0:4005
      path: /callback
      heartbeat_interval: 15s
      subgraphs:
        - messages